-- Create vendor_sends table with exact specifications
CREATE TABLE IF NOT EXISTS public.vendor_sends (
    id bigint generated by default as identity not null,
    request_id bigint not null,
    vendor_id uuid not null,
    sent_at timestamp with time zone not null default now(),
    status text null default 'sent'::text,
    front_image_url text null,
    back_image_url text null,
    card_details jsonb null,
    vendor_status character varying(50) null default 'sent'::character varying,
    constraint vendor_sends_pkey primary key (id),
    constraint vendor_sends_request_id_fkey foreign KEY (request_id) references requests (id) on delete CASCADE,
    constraint vendor_sends_vendor_id_fkey foreign KEY (vendor_id) references vendors (id) on delete CASCADE,
    constraint check_vendor_status check (
        (
            (vendor_status)::text = any (
                (
                    array[
                        'sent'::character varying,
                        'accepted'::character varying,
                        'rejected'::character varying
                    ]
                )::text[]
            )
        )
    )
) TABLESPACE pg_default;

-- Create indexes as specified
CREATE INDEX IF NOT EXISTS idx_vendor_sends_vendor_status ON public.vendor_sends USING btree (vendor_status) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_vendor_sends_vendor_status_combo ON public.vendor_sends USING btree (vendor_id, vendor_status) TABLESPACE pg_default;
