-- Fix storage bucket and schema issues for vendor_sends
-- This migration ensures the storage bucket exists and schema is correct

-- Create storage bucket for ID card images if it doesn't exist
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('id-card-images', 'id-card-images', true, 5242880, ARRAY['image/png', 'image/jpeg', 'image/jpg'])
ON CONFLICT (id) DO NOTHING;

-- Verify the current vendor_sends schema matches the new requirements
-- If the table has the old schema, we need to migrate it
DO $$
BEGIN
    -- Check if vendor_sends has the old schema (request_ids array)
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'vendor_sends' 
        AND column_name = 'request_ids'
    ) THEN
        -- Backup existing data
        CREATE TABLE vendor_sends_migration_backup AS SELECT * FROM vendor_sends;
        
        -- Drop the old table
        DROP TABLE vendor_sends CASCADE;
        
        -- Create new table with correct schema
        CREATE TABLE public.vendor_sends (
            id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            request_id bigint NOT NULL,
            vendor_id uuid NOT NULL,
            sent_at timestamp with time zone NOT NULL DEFAULT now(),
            status text NULL DEFAULT 'sent'::text,
            front_image_url text NULL,
            back_image_url text NULL,
            card_details jsonb NULL,
            vendor_status character varying(50) NULL DEFAULT 'sent'::character varying,
            CONSTRAINT vendor_sends_pkey PRIMARY KEY (id),
            CONSTRAINT vendor_sends_request_id_fkey FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE CASCADE,
            CONSTRAINT vendor_sends_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES vendors (id) ON DELETE CASCADE,
            CONSTRAINT check_vendor_status CHECK (
                (
                    (vendor_status)::text = ANY (
                        (
                            ARRAY[
                                'sent'::character varying,
                                'accepted'::character varying,
                                'rejected'::character varying
                            ]
                        )::text[]
                    )
                )
            )
        ) TABLESPACE pg_default;
        
        -- Create indexes
        CREATE INDEX idx_vendor_sends_vendor_status ON public.vendor_sends USING btree (vendor_status) TABLESPACE pg_default;
        CREATE INDEX idx_vendor_sends_vendor_status_combo ON public.vendor_sends USING btree (vendor_id, vendor_status) TABLESPACE pg_default;
        
        -- Enable RLS
        ALTER TABLE public.vendor_sends ENABLE ROW LEVEL SECURITY;
        
        -- Add RLS policies
        CREATE POLICY "Vendor sends are viewable by assigned vendors" ON public.vendor_sends
            FOR SELECT TO authenticated USING (
                EXISTS (
                    SELECT 1 FROM public.profiles
                    WHERE profiles.id = auth.uid() AND profiles.role = 'vendor' AND vendor_sends.vendor_id = profiles.id
                )
            );

        CREATE POLICY "Vendor sends are viewable by admins" ON public.vendor_sends
            FOR SELECT TO authenticated USING (
                EXISTS (
                    SELECT 1 FROM public.profiles
                    WHERE profiles.id = auth.uid() AND (profiles.role = 'admin' OR profiles.role = 'manager')
                )
            );

        CREATE POLICY "Vendor sends are manageable by admins" ON public.vendor_sends
            FOR ALL TO authenticated USING (
                EXISTS (
                    SELECT 1 FROM public.profiles
                    WHERE profiles.id = auth.uid() AND (profiles.role = 'admin' OR profiles.role = 'manager')
                )
            );
        
        RAISE NOTICE 'vendor_sends table migrated from old schema to new schema';
    END IF;
END $$;

-- Ensure vendors table has correct structure (uuid primary key)
DO $$
BEGIN
    -- Check if vendors table has bigint id instead of uuid
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'vendors' 
        AND column_name = 'id' 
        AND data_type = 'bigint'
    ) THEN
        RAISE NOTICE 'vendors table needs to be migrated from bigint to uuid';
        
        -- This is a complex migration that would require updating all foreign keys
        -- For now, we'll just note that it needs to be done
        -- In production, this would need careful planning
    END IF;
END $$;

-- Grant necessary permissions
GRANT ALL ON TABLE public.vendor_sends TO authenticated;
GRANT ALL ON TABLE public.vendor_sends TO service_role;
GRANT ALL ON SEQUENCE public.vendor_sends_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.vendor_sends_id_seq TO service_role;