


-- 2. Fix vendors table to use UUID and reference profiles
DROP TABLE IF EXISTS public.vendors CASCADE;

CREATE TABLE public.vendors (
    id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    name text NOT NULL,
    email text NOT NULL UNIQUE,
    address text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS
ALTER TABLE public.vendors ENABLE ROW LEVEL SECURITY;

-- Add policies for vendors
CREATE POLICY "Vendors are viewable by authenticated users" ON public.vendors
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Vendors are manageable by admins" ON public.vendors
    FOR ALL TO authenticated USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid()
            AND (profiles.role = 'admin' OR profiles.role = 'manager')
        )
    );

-- 3. Update handle_new_user function to support role from metadata
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role, branch)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'full_name',
    COALESCE((NEW.raw_user_meta_data->>'role')::public.user_role_enum, 'user'::public.user_role_enum),
    (NEW.raw_user_meta_data->>'branch')::public.branch_enum
  ) ON CONFLICT (id) DO UPDATE SET
    role = EXCLUDED.role,
    full_name = EXCLUDED.full_name,
    branch = EXCLUDED.branch;

  -- Insert a new employee record if employee_id is present
  IF NEW.raw_user_meta_data->>'employee_id' IS NOT NULL THEN
    INSERT INTO public.employees (name, employee_id, branch, email, created_by)
    VALUES (
      NEW.raw_user_meta_data->>'full_name',
      NEW.raw_user_meta_data->>'employee_id',
      (NEW.raw_user_meta_data->>'branch')::public.branch_enum,
      NEW.email,
      NEW.id
    ) ON CONFLICT (employee_id) DO NOTHING;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Update handle_user_update function to support role
CREATE OR REPLACE FUNCTION public.handle_user_update()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.raw_user_meta_data <> NEW.raw_user_meta_data OR OLD.email <> NEW.email THEN
    UPDATE public.profiles
    SET
      full_name = NEW.raw_user_meta_data->>'full_name',
      role = COALESCE((NEW.raw_user_meta_data->>'role')::public.user_role_enum, profiles.role),
      branch = (NEW.raw_user_meta_data->>'branch')::public.branch_enum
    WHERE id = NEW.id;

    UPDATE public.employees
    SET
      name = NEW.raw_user_meta_data->>'full_name',
      branch = (NEW.raw_user_meta_data->>'branch')::public.branch_enum,
      email = NEW.email
    WHERE created_by = NEW.id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Add RLS for profiles if missing
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

-- 6. Fix vendor_sends table
DROP TABLE IF EXISTS public.vendor_sends CASCADE;

CREATE TABLE public.vendor_sends (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id bigint NOT NULL REFERENCES public.requests(id) ON DELETE CASCADE,
    vendor_id uuid NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE,
    sent_at timestamp with time zone DEFAULT now() NOT NULL,
    status text DEFAULT 'sent'
);

-- Enable RLS
ALTER TABLE public.vendor_sends ENABLE ROW LEVEL SECURITY;

-- Add policies for vendor_sends
CREATE POLICY "Vendor sends are viewable by assigned vendors" ON public.vendor_sends
    FOR SELECT TO authenticated USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role = 'vendor' AND vendor_sends.vendor_id = profiles.id
        )
    );

CREATE POLICY "Vendor sends are viewable by admins" ON public.vendor_sends
    FOR SELECT TO authenticated USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND (profiles.role = 'admin' OR profiles.role = 'manager')
        )
    );

CREATE POLICY "Vendor sends are manageable by admins" ON public.vendor_sends
    FOR ALL TO authenticated USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND (profiles.role = 'admin' OR profiles.role = 'manager')
        )
    );