-- Update vendor_sends table to match the required schema
-- This migration should be run after the initial schema setup

-- First, check if vendor_sends table exists and backup data if needed
DO $$
BEGIN
    -- Check if vendor_sends table exists
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'vendor_sends') THEN
        -- Create a backup table if vendor_sends exists
        CREATE TABLE IF NOT EXISTS vendor_sends_backup AS SELECT * FROM vendor_sends;
        RAISE NOTICE 'vendor_sends table backed up to vendor_sends_backup';
    END IF;
END $$;

-- Drop existing vendor_sends table if it exists
DROP TABLE IF EXISTS public.vendor_sends CASCADE;

-- Create vendor_sends table with the new schema
CREATE TABLE public.vendor_sends (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  request_id bigint NOT NULL,
  vendor_id uuid NOT NULL,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NULL DEFAULT 'sent'::text,
  front_image_url text NULL,
  back_image_url text NULL,
  card_details jsonb NULL,
  vendor_status character varying(50) NULL DEFAULT 'sent'::character varying,
  CONSTRAINT vendor_sends_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_sends_request_id_fkey FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE CASCADE,
  CONSTRAINT vendor_sends_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES vendors (id) ON DELETE CASCADE,
  CONSTRAINT check_vendor_status CHECK (
    (
      (vendor_status)::text = ANY (
        (
          ARRAY[
            'sent'::character varying,
            'accepted'::character varying,
            'rejected'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_vendor_sends_vendor_status ON public.vendor_sends USING btree (vendor_status) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_vendor_sends_vendor_status_combo ON public.vendor_sends USING btree (vendor_id, vendor_status) TABLESPACE pg_default;

-- Enable RLS
ALTER TABLE public.vendor_sends ENABLE ROW LEVEL SECURITY;

-- Add policies for vendor_sends
CREATE POLICY "Vendor sends are viewable by assigned vendors" ON public.vendor_sends
    FOR SELECT TO authenticated USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role = 'vendor' AND vendor_sends.vendor_id = profiles.id
        )
    );

CREATE POLICY "Vendor sends are viewable by admins" ON public.vendor_sends
    FOR SELECT TO authenticated USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND (profiles.role = 'admin' OR profiles.role = 'manager')
        )
    );

CREATE POLICY "Vendor sends are manageable by admins" ON public.vendor_sends
    FOR ALL TO authenticated USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND (profiles.role = 'admin' OR profiles.role = 'manager')
        )
    );

-- Restore data from backup if it exists
DO $$
BEGIN
    -- Check if backup table exists and has data
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'vendor_sends_backup') THEN
        -- Insert data from backup, handling any schema differences
        -- Check if the backup table has the old schema (request_ids array) or new schema (request_id)
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'vendor_sends_backup' AND column_name = 'request_ids') THEN
            -- Old schema with request_ids array
            INSERT INTO vendor_sends (
                request_id, 
                vendor_id, 
                sent_at, 
                status, 
                front_image_url, 
                back_image_url, 
                card_details, 
                vendor_status
            )
            SELECT 
                request_ids[1] as request_id,  -- Convert array to single value
                vendor_id,
                created_at as sent_at,
                'sent' as status,
                NULL as front_image_url,
                NULL as back_image_url,
                NULL as card_details,
                'sent' as vendor_status
            FROM vendor_sends_backup
            WHERE array_length(request_ids, 1) > 0;
        ELSE
            -- New schema with request_id (singular)
            -- Check what timestamp column exists in the backup table
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'vendor_sends_backup' AND column_name = 'sent_at') THEN
                INSERT INTO vendor_sends (
                    request_id, 
                    vendor_id, 
                    sent_at, 
                    status, 
                    front_image_url, 
                    back_image_url, 
                    card_details, 
                    vendor_status
                )
                SELECT 
                    request_id,
                    vendor_id,
                    sent_at,
                    'sent' as status,
                    NULL as front_image_url,
                    NULL as back_image_url,
                    NULL as card_details,
                    'sent' as vendor_status
                FROM vendor_sends_backup;
            ELSE
                -- Fallback to current timestamp if no timestamp column exists
                INSERT INTO vendor_sends (
                    request_id, 
                    vendor_id, 
                    sent_at, 
                    status, 
                    front_image_url, 
                    back_image_url, 
                    card_details, 
                    vendor_status
                )
                SELECT 
                    request_id,
                    vendor_id,
                    now() as sent_at,
                    'sent' as status,
                    NULL as front_image_url,
                    NULL as back_image_url,
                    NULL as card_details,
                    'sent' as vendor_status
                FROM vendor_sends_backup;
            END IF;
        END IF;
        
        RAISE NOTICE 'Data restored from vendor_sends_backup';
        
        -- Drop backup table after successful restore
        DROP TABLE vendor_sends_backup;
    END IF;
END $$;
