-- Update vendor_sends table to ensure proper schema and policies
-- This migration handles cases where the table may already exist

DROP TABLE IF EXISTS public.vendor_sends CASCADE;

-- Ensure the table exists with correct schema
CREATE TABLE public.vendor_sends (
    id bigint generated by default as identity not null,
    request_id bigint not null,
    vendor_id uuid not null,
    sent_at timestamp with time zone not null default now(),
    status text null default 'sent'::text,
    front_image_url text null,
    back_image_url text null,
    card_details jsonb null,
    vendor_status character varying(50) null default 'sent'::character varying,
    constraint vendor_sends_pkey primary key (id),
    constraint vendor_sends_request_id_fkey foreign KEY (request_id) references requests (id) on delete CASCADE,
    constraint vendor_sends_vendor_id_fkey foreign KEY (vendor_id) references vendors (id) on delete CASCADE,
    constraint check_vendor_status check (
        (
            (vendor_status)::text = any (
                (
                    array[
                        'sent'::character varying,
                        'accepted'::character varying,
                        'rejected'::character varying
                    ]
                )::text[]
            )
        )
    )
) TABLESPACE pg_default;

-- Create indexes if they don't exist
CREATE INDEX IF NOT EXISTS idx_vendor_sends_vendor_status ON public.vendor_sends USING btree (vendor_status) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_vendor_sends_vendor_status_combo ON public.vendor_sends USING btree (vendor_id, vendor_status) TABLESPACE pg_default;

-- Enable RLS if not already enabled
ALTER TABLE public.vendor_sends ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist and recreate them
DROP POLICY IF EXISTS "Vendor sends are viewable by assigned vendors" ON public.vendor_sends;
DROP POLICY IF EXISTS "Vendor sends are viewable by admins" ON public.vendor_sends;
DROP POLICY IF EXISTS "Vendor sends are manageable by admins" ON public.vendor_sends;
DROP POLICY IF EXISTS "Vendors can update their own sends" ON public.vendor_sends;

-- Add policies for vendor_sends
CREATE POLICY "Vendor sends are viewable by assigned vendors" ON public.vendor_sends
    FOR SELECT TO authenticated USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role = 'vendor' AND vendor_sends.vendor_id = profiles.id
        )
    );

CREATE POLICY "Vendor sends are viewable by admins" ON public.vendor_sends
    FOR SELECT TO authenticated USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND (profiles.role = 'admin' OR profiles.role = 'manager')
        )
    );

CREATE POLICY "Vendor sends are manageable by admins" ON public.vendor_sends
    FOR ALL TO authenticated USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND (profiles.role = 'admin' OR profiles.role = 'manager')
        )
    );

CREATE POLICY "Vendors can update their own sends" ON public.vendor_sends
    FOR UPDATE TO authenticated USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role = 'vendor' AND vendor_sends.vendor_id = profiles.id
        )
    ) WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role = 'vendor' AND vendor_sends.vendor_id = profiles.id
        )
    );