-- Migration: 016_fix_vendor_requests_schema
-- Purpose: Ensure vendor_requests table has the correct schema, including nullable request_id and zip_url.

DO $$
BEGIN
    -- 1. Rename vendor_sends to vendor_requests if vendor_requests doesn't exist but vendor_sends does
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'vendor_sends') 
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'vendor_requests') THEN
        ALTER TABLE public.vendor_sends RENAME TO vendor_requests;
        RAISE NOTICE 'Renamed vendor_sends to vendor_requests';
    END IF;

    -- 2. Create vendor_requests if it still doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'vendor_requests') THEN
        CREATE TABLE public.vendor_requests (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            request_id bigint REFERENCES public.requests(id) ON DELETE CASCADE,
            vendor_id uuid NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE,
            sent_at timestamp with time zone DEFAULT now() NOT NULL,
            status text DEFAULT 'sent',
            front_image_url text,
            back_image_url text,
            card_details jsonb,
            vendor_status text DEFAULT 'sent',
            batch_id text REFERENCES public.card_batches(batch_id) ON DELETE CASCADE,
            zip_url text,
            id_card_id bigint REFERENCES public.id_cards(id) ON DELETE CASCADE
        );
        RAISE NOTICE 'Created vendor_requests table';
    ELSE
        -- 3. Ensure all columns exist and are of correct type/nullability
        
        -- Make request_id nullable
        ALTER TABLE public.vendor_requests ALTER COLUMN request_id DROP NOT NULL;
        
        -- Add missing columns
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vendor_requests' AND column_name = 'zip_url') THEN
            ALTER TABLE public.vendor_requests ADD COLUMN zip_url text;
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vendor_requests' AND column_name = 'id_card_id') THEN
            ALTER TABLE public.vendor_requests ADD COLUMN id_card_id bigint REFERENCES public.id_cards(id) ON DELETE CASCADE;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vendor_requests' AND column_name = 'batch_id') THEN
            ALTER TABLE public.vendor_requests ADD COLUMN batch_id text REFERENCES public.card_batches(batch_id) ON DELETE CASCADE;
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vendor_requests' AND column_name = 'front_image_url') THEN
            ALTER TABLE public.vendor_requests ADD COLUMN front_image_url text;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vendor_requests' AND column_name = 'back_image_url') THEN
            ALTER TABLE public.vendor_requests ADD COLUMN back_image_url text;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vendor_requests' AND column_name = 'card_details') THEN
            ALTER TABLE public.vendor_requests ADD COLUMN card_details jsonb;
        END IF;
    END IF;
END $$;

-- 4. Record migration
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'schema_migrations') THEN
        INSERT INTO public.schema_migrations (version, name, executed_at) 
        VALUES ('016_fix_vendor_requests_schema', 'Fix vendor_requests schema and nullability', now())
        ON CONFLICT (version) DO NOTHING;
    END IF;
END $$;
