-- Create vendor_requests table with RLS policies
-- This migration sets up the vendor_requests table with proper RLS

-- Step 1: Create the vendor_requests table
CREATE TABLE IF NOT EXISTS public.vendor_requests (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  request_id bigint null,
  vendor_id uuid null,
  status character varying null default 'sent'::character varying,
  front_image_url text null,
  back_image_url text null,
  card_details jsonb null,
  sent_at timestamp with time zone null default now(),
  batch_id text null,
  zip_url text null,
  id_card_id bigint null,
  card_details_id bigint null,
  source_table text null default 'requests'::text,
  constraint vendor_requests_pkey primary key (id),
  constraint vendor_requests_card_details_id_fkey foreign key (card_details_id) references card_details (id) on delete cascade,
  constraint vendor_requests_id_card_id_fkey foreign key (id_card_id) references id_cards (id) on delete cascade,
  constraint vendor_requests_batch_id_fkey foreign key (batch_id) references card_batches (batch_id) on delete cascade,
  constraint vendor_requests_request_id_fkey foreign key (request_id) references requests (id) ON DELETE SET NULL,
  constraint vendor_requests_vendor_id_fkey foreign key (vendor_id) references vendors (id),
  constraint vendor_requests_source_table_check check (
    (
      source_table = any (array['requests'::text, 'card_details'::text])
    )
  )
) tablespace pg_default;

-- Step 2: Create indexes
CREATE INDEX IF NOT EXISTS idx_vendor_requests_card_details_id ON public.vendor_requests USING btree (card_details_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_vendor_requests_source_table ON public.vendor_requests USING btree (source_table) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_vendor_requests_vendor_source ON public.vendor_requests USING btree (vendor_id, source_table) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_vendor_requests_vendor_id ON public.vendor_requests USING btree (vendor_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_vendor_requests_status ON public.vendor_requests USING btree (status) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_vendor_requests_created_at ON public.vendor_requests USING btree (created_at DESC) TABLESPACE pg_default;

-- Step 3: Enable RLS
ALTER TABLE public.vendor_requests ENABLE ROW LEVEL SECURITY;

-- Step 4: Drop existing policies if they exist
DROP POLICY IF EXISTS "Service role access all vendor requests" ON public.vendor_requests;
DROP POLICY IF EXISTS "Vendors can view their own requests" ON public.vendor_requests;
DROP POLICY IF EXISTS "Admins managers view all vendor requests" ON public.vendor_requests;
DROP POLICY IF EXISTS "Vendors can update their own requests" ON public.vendor_requests;
DROP POLICY IF EXISTS "Admins managers update all requests" ON public.vendor_requests;
DROP POLICY IF EXISTS "Service role insert vendor requests" ON public.vendor_requests;
DROP POLICY IF EXISTS "Admins managers insert vendor requests" ON public.vendor_requests;
DROP POLICY IF EXISTS "Admins delete vendor requests" ON public.vendor_requests;
-- Backwards-compatible: drop legacy/alternate policy names too
DROP POLICY IF EXISTS "Admins and managers can view all requests" ON public.vendor_requests;
DROP POLICY IF EXISTS "Users can view status of their own cards" ON public.vendor_requests;
DROP POLICY IF EXISTS "Admins can manage all requests" ON public.vendor_requests;
DROP POLICY IF EXISTS "Admins can update all requests" ON public.vendor_requests;
DROP POLICY IF EXISTS "Admins can delete requests" ON public.vendor_requests;
DROP POLICY IF EXISTS "Admins and vendors can insert vendor requests" ON public.vendor_requests;
DROP POLICY IF EXISTS "Admins can insert vendor requests" ON public.vendor_requests;
DROP POLICY IF EXISTS "Authenticated users can insert vendor requests" ON public.vendor_requests;

-- Step 5: Create RLS Policies
-- IMPORTANT: Use auth.jwt() to avoid recursive subqueries on profiles table

-- Policy 1: SELECT - Service role can see all (for backend operations)
CREATE POLICY "Service role access all vendor requests" 
  ON public.vendor_requests 
  FOR SELECT 
  TO service_role 
  USING (true);

-- Policy 2: SELECT - Vendors can see requests assigned to them
CREATE POLICY "Vendors can view their own requests" 
  ON public.vendor_requests 
  FOR SELECT 
  TO authenticated 
  USING (
    vendor_id = auth.uid()
  );

-- Policy 3: SELECT - Admins and managers can see all
CREATE POLICY "Admins managers view all vendor requests" 
  ON public.vendor_requests 
  FOR SELECT 
  TO authenticated 
  USING (
    get_user_role(auth.uid()) IN ('admin', 'manager')
  );

-- Policy 4: UPDATE - Vendors can update their own requests
CREATE POLICY "Vendors can update their own requests" 
  ON public.vendor_requests 
  FOR UPDATE 
  TO authenticated 
  USING (
    vendor_id = auth.uid()
  )
  WITH CHECK (
    vendor_id = auth.uid()
  );

-- Policy 5: UPDATE - Admins and managers can update all requests
CREATE POLICY "Admins managers update all requests" 
  ON public.vendor_requests 
  FOR UPDATE 
  TO authenticated 
  USING (
    get_user_role(auth.uid()) IN ('admin', 'manager')
  )
  WITH CHECK (
    get_user_role(auth.uid()) IN ('admin', 'manager')
  );

-- Policy 6: INSERT - Service role can insert (for backend operations)
CREATE POLICY "Service role insert vendor requests" 
  ON public.vendor_requests 
  FOR INSERT 
  TO service_role 
  WITH CHECK (true);

-- Policy 7: INSERT - Admins and managers can insert
CREATE POLICY "Admins managers insert vendor requests" 
  ON public.vendor_requests 
  FOR INSERT 
  TO authenticated 
  WITH CHECK (
    get_user_role(auth.uid()) IN ('admin', 'manager')
  );

-- Policy 8: DELETE - Admins only
CREATE POLICY "Admins delete vendor requests" 
  ON public.vendor_requests 
  FOR DELETE 
  TO authenticated 
  USING (
    get_user_role(auth.uid()) = 'admin'
  );

-- Step 6: Grant permissions
GRANT SELECT, UPDATE, INSERT ON public.vendor_requests TO authenticated;
GRANT ALL ON public.vendor_requests TO service_role;

-- Log migration
SELECT 'vendor_requests table created with RLS policies enabled' as migration_status;
