CREATE TABLE vendor_sends (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    vendor_id bigint REFERENCES vendors(id) NOT NULL,
    request_ids bigint[] NOT NULL,
    id_count integer GENERATED ALWAYS AS (cardinality(request_ids)) STORED
);