-- Migration: 032_create_accessory_orders
-- Purpose: Create accessory_orders table for admin to order lanyards/card holders from vendors

-- Create the accessory_orders table
CREATE TABLE IF NOT EXISTS public.accessory_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    vendor_id uuid REFERENCES public.vendors(id) ON DELETE SET NULL,
    lanyard_count integer NOT NULL DEFAULT 0,
    holder_count integer NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'sent', 'completed')),
    created_by uuid REFERENCES auth.users(id) NOT NULL,
    notes text,
    CONSTRAINT positive_count CHECK (lanyard_count >= 0 AND holder_count >= 0)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_accessory_orders_vendor_id ON public.accessory_orders USING btree (vendor_id);
CREATE INDEX IF NOT EXISTS idx_accessory_orders_status ON public.accessory_orders USING btree (status);
CREATE INDEX IF NOT EXISTS idx_accessory_orders_created_by ON public.accessory_orders USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_accessory_orders_created_at ON public.accessory_orders USING btree (created_at DESC);

-- Enable RLS
ALTER TABLE public.accessory_orders ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Admins can manage all accessory orders" ON public.accessory_orders;
DROP POLICY IF EXISTS "Vendors can view their own accessory orders" ON public.accessory_orders;
DROP POLICY IF EXISTS "Vendors can update their own accessory orders" ON public.accessory_orders;

-- Policy: Admins/managers/super_admins can manage all accessory orders
CREATE POLICY "Admins can manage all accessory orders"
    ON public.accessory_orders
    FOR ALL
    TO authenticated
    USING (
        public.get_user_role(auth.uid()) IN ('admin', 'manager') OR public.is_super_admin()
    )
    WITH CHECK (
        public.get_user_role(auth.uid()) IN ('admin', 'manager') OR public.is_super_admin()
    );

-- Policy: Vendors can view their own orders
CREATE POLICY "Vendors can view their own accessory orders"
    ON public.accessory_orders
    FOR SELECT
    TO authenticated
    USING (
        vendor_id = auth.uid()
    );

-- Policy: Vendors can update their own orders (status transitions)
CREATE POLICY "Vendors can update their own accessory orders"
    ON public.accessory_orders
    FOR UPDATE
    TO authenticated
    USING (
        vendor_id = auth.uid()
    )
    WITH CHECK (
        vendor_id = auth.uid()
    );

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON public.accessory_orders TO authenticated;
GRANT USAGE ON SEQUENCE public.accessory_orders_id_seq TO authenticated;
GRANT ALL ON public.accessory_orders TO service_role;
GRANT ALL ON SEQUENCE public.accessory_orders_id_seq TO service_role;

-- Trigger to auto-update updated_at
CREATE OR REPLACE FUNCTION public.update_accessory_orders_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_accessory_orders_updated_at ON public.accessory_orders;
CREATE TRIGGER trg_accessory_orders_updated_at
    BEFORE UPDATE ON public.accessory_orders
    FOR EACH ROW
    EXECUTE FUNCTION public.update_accessory_orders_updated_at();

-- Record migration
DO $$
BEGIN
    INSERT INTO public.schema_migrations (version, name, executed_at)
    VALUES ('032_create_accessory_orders', 'Create accessory_orders table for lanyard/card holder orders', now())
    ON CONFLICT (version) DO NOTHING;
EXCEPTION WHEN undefined_table THEN
    RAISE NOTICE 'schema_migrations table does not exist, skipping migration record';
END $$;
